# Generated by Django 5.0.6 on 2026-03-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmembership',
            name='require_payment_confirmation',
            field=models.BooleanField(default=False, help_text='If True, the payer must confirm before a split is fully settled.'),
        ),
    ]
