# Generated by Django 5.0.6 on 2026-03-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_deactivated_at_user_is_platform_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
