# Generated by Django 5.0.6 on 2026-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='proportion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Relative weight for proportion-based splits', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Equal Split'), ('custom', 'Custom Amounts'), ('percentage', 'Percentage'), ('proportion', 'Proportion (e.g. 2:1:1)')], default='equal', max_length=15),
        ),
    ]
