# Generated by Django 5.0.6 on 2026-03-04 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='is_rotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chore',
            name='rotation_members',
            field=models.ManyToManyField(blank=True, related_name='rotation_chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chore',
            name='rotation_order',
            field=models.PositiveSmallIntegerField(default=0, help_text="Index of who is currently 'up' in the rotation list"),
        ),
        migrations.AlterField(
            model_name='chore',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None (one-time)'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='chore',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('done', 'Done')], default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='chorelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('reassigned', 'Reassigned'), ('reassign_requested', 'Reassign Requested'), ('swap_requested', 'Swap Requested'), ('swap_approved', 'Swap Approved'), ('note_edited', 'Note Edited')], max_length=25),
        ),
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chore_assignments', to=settings.AUTH_USER_MODEL)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.chore')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chore_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='chorelog',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='chores.choreassignment'),
        ),
    ]
