# Generated by Django 5.0.6 on 2026-03-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chore_is_rotation_chore_rotation_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None (one-time)'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('until_closed', 'Until closed by admin')], default='none', max_length=15),
        ),
    ]
